echo "to see the PID: $$"
echo " To see the file name: $0"
echo " to see the 1st arrugunet $1"
echo " to see the number of arrgment passed in the scrpit $# "
echo " all arr are double quoted $*"
echo " all arr are individually  double quoted $@"
echo " to see the exit command $?"
echo " to see the PID of the last command $!"
